apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: appointment-webapp
spec:
  selector:
    matchLabels:
      app: appointment-webapp
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: appointment-webapp
    spec:
      containers:
        - name: appointment-webapp
          image: appointment-webapp:v5
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: HEALTH_CONNECT_2022
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: appointment-service
spec:
  selector:
    app: appointment-webapp
  ports:
    - protocol: "TCP"
      port: 8086 # The port that the service is running on in the cluster
      targetPort: 8086 # The port exposed by the service
      name: http
  type: NodePort # type of the service.